const list = [
    {
        flag: '0x14',
        group: 'none',
        index: '0x17',
        index10: 23,
        des: '微笑',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x28',
        index10: 40,
        des: '撇嘴',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x13',
        index10: 19,
        des: '色',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x2b',
        index10: 43,
        des: '发呆',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x15',
        index10: 21,
        des: '得意',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x9',
        index10: 9,
        des: '流泪',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x14',
        index10: 20,
        des: '害羞',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x6a',
        index10: 106,
        des: '闭嘴',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x23',
        index10: 35,
        des: '睡',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0xba',
        index10: 186,
        des: '大哭',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x19',
        index10: 25,
        des: '尴尬',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x18',
        index10: 24,
        des: '发怒',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x1',
        index10: 1,
        des: '调皮',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x0',
        index10: 0,
        des: '呲牙',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x21',
        index10: 33,
        des: '惊讶',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x20',
        index10: 32,
        des: '难过',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0xc',
        index10: 12,
        des: '酷',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x1b',
        index10: 27,
        des: '冷汗',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0xd',
        index10: 13,
        des: '抓狂',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x16',
        index10: 22,
        des: '吐',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x3',
        index10: 3,
        des: '偷笑',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x12',
        index10: 18,
        des: '可爱',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x1e',
        index10: 30,
        des: '白眼',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x1f',
        index10: 31,
        des: '傲慢',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x51',
        index10: 81,
        des: '饥饿',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x52',
        index10: 82,
        des: '困',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x1a',
        index10: 26,
        des: '惊恐',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x2',
        index10: 2,
        des: '流汗',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x25',
        index10: 37,
        des: '憨笑',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x32',
        index10: 50,
        des: '大兵',
        nDes: '悠闲',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x2a',
        index10: 42,
        des: '奋斗',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x53',
        index10: 83,
        des: '咒骂',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x22',
        index10: 34,
        des: '疑问',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0xb',
        index10: 11,
        des: '嘘',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x31',
        index10: 49,
        des: '晕',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x54',
        index10: 84,
        des: '折磨',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x27',
        index10: 39,
        des: '衰',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x4e',
        index10: 78,
        des: '骷髅',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x5',
        index10: 5,
        des: '敲打',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x4',
        index10: 4,
        des: '再见',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x6',
        index10: 6,
        des: '擦汗',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x55',
        index10: 85,
        des: '抠鼻',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x56',
        index10: 86,
        des: '鼓掌',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x57',
        index10: 87,
        des: '糗大了',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x2e',
        index10: 46,
        des: '坏笑',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x58',
        index10: 88,
        des: '左哼哼',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x2c',
        index10: 44,
        des: '右哼哼',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x59',
        index10: 89,
        des: '哈欠',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x30',
        index10: 48,
        des: '鄙视',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0xe',
        index10: 14,
        des: '委屈',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x5a',
        index10: 90,
        des: '快哭了',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x29',
        index10: 41,
        des: '阴险',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0xb1',
        index10: 177,
        des: '右亲亲',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x24',
        index10: 36,
        des: '亲亲',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x33',
        index10: 51,
        des: '可怜',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xa4',
        index10: 164,
        des: '眨眼睛',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xae',
        index10: 174,
        des: '笑哭',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xab',
        index10: 171,
        des: 'doge',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xa5',
        index10: 165,
        des: '泪奔',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xa6',
        index10: 166,
        des: '无奈',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xa1',
        index10: 161,
        des: '托腮',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xa7',
        index10: 167,
        des: '卖萌',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xaa',
        index10: 170,
        des: '斜眼笑',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xa9',
        index10: 169,
        des: '喷血',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xac',
        index10: 172,
        des: '惊喜',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xad',
        index10: 173,
        des: '骚扰',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xa8',
        index10: 168,
        des: '小纠结',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xaf',
        index10: 175,
        des: '我最美',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x99',
        index10: 153,
        des: '加油必胜',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x9a',
        index10: 154,
        des: '加油抱抱',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x9b',
        index10: 155,
        des: '口罩护体',
        ext: 'png',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0x84',
        index10: 132,
        des: '搬砖中',
        ext: 'png',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0x85',
        index10: 133,
        des: '忙到飞起',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0x86',
        index10: 134,
        des: '脑阔疼',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0x87',
        index10: 135,
        des: '沧桑',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0x88',
        index10: 136,
        des: '捂脸',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0x89',
        index10: 137,
        des: '辣眼睛',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0x8a',
        index10: 138,
        des: '哦哟',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0x8b',
        index10: 139,
        des: '头秃',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0x8c',
        index10: 140,
        des: '问号脸',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0x8d',
        index10: 141,
        des: '暗中观察',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0x8e',
        index10: 142,
        des: 'emm',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0x8f',
        index10: 143,
        des: '吃瓜',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0x90',
        index10: 144,
        des: '呵呵哒',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0x95',
        index10: 149,
        des: '汪汪',
        ext: 'gif',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0xb3',
        index10: 179,
        des: '喵喵',
        ext: 'gif',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0xb2',
        index10: 178,
        des: '牛气冲天',
        ext: 'gif',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0x99',
        index10: 153,
        des: '无眼笑',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0x9a',
        index10: 154,
        des: '敬礼',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0x9b',
        index10: 155,
        des: '狂笑',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0x9c',
        index10: 156,
        des: '面无表情',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0x9d',
        index10: 157,
        des: '摸鱼',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0xa5',
        index10: 165,
        des: '摸锦鲤',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0x9e',
        index10: 158,
        des: '魔鬼笑',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0x9f',
        index10: 159,
        des: '哦',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0xa0',
        index10: 160,
        des: '请',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0xa1',
        index10: 161,
        des: '睁眼',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0xa6',
        index10: 166,
        des: '期待',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0xa7',
        index10: 167,
        des: '拿到红包',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0xa8',
        index10: 168,
        des: '真好',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0xa9',
        index10: 169,
        des: '拜谢',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0xaa',
        index10: 170,
        des: '元宝',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0xab',
        index10: 171,
        des: '牛啊',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0xac',
        index10: 172,
        des: '胖三斤',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0xad',
        index10: 173,
        des: '好闪',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0xaf',
        index10: 175,
        des: '右拜年',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0xae',
        index10: 174,
        des: '左拜年',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0xb0',
        index10: 176,
        des: '红包包',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xb8',
        index10: 184,
        des: '红包',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x6d',
        index10: 109,
        des: '鞭炮',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x6e',
        index10: 110,
        des: '灯笼',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x6c',
        index10: 108,
        des: '双喜',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0x91',
        index10: 145,
        des: '我酸了',
        ext: 'png',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0x92',
        index10: 146,
        des: '太南了',
        ext: 'gif',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x11',
        index10: 17,
        des: '菜刀',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x3c',
        index10: 60,
        des: '西瓜',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x3d',
        index10: 61,
        des: '啤酒',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x5c',
        index10: 92,
        des: '篮球',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x5d',
        index10: 93,
        des: '乒乓',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xa3',
        index10: 163,
        des: '茶',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x42',
        index10: 66,
        des: '咖啡',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x3a',
        index10: 58,
        des: '饭',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x7',
        index10: 7,
        des: '猪头',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x8',
        index10: 8,
        des: '玫瑰',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x39',
        index10: 57,
        des: '凋谢',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x1d',
        index10: 29,
        des: '示爱',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x1c',
        index10: 28,
        des: '心',
        nDes: '爱心',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x4a',
        index10: 74,
        des: '心碎',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x3b',
        index10: 59,
        des: '蛋糕',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x50',
        index10: 80,
        des: '闪电',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x10',
        index10: 16,
        des: '炸弹',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x46',
        index10: 70,
        des: '刀',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x75',
        index10: 117,
        des: '祈祷',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x4d',
        index10: 77,
        des: '足球',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x3e',
        index10: 62,
        des: '瓢虫',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0xf',
        index10: 15,
        des: '便便',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x44',
        index10: 68,
        des: '月亮',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x4b',
        index10: 75,
        des: '太阳',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x4c',
        index10: 76,
        des: '礼物',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x2d',
        index10: 45,
        des: '拥抱',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x34',
        index10: 52,
        des: '强',
        nDes: '赞',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x35',
        index10: 53,
        des: '弱',
        nDes: '踩',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x36',
        index10: 54,
        des: '握手',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x37',
        index10: 55,
        des: '胜利',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x38',
        index10: 56,
        des: '抱拳',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x3f',
        index10: 63,
        des: '勾引',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x49',
        index10: 73,
        des: '拳头',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x48',
        index10: 72,
        des: '差劲',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x41',
        index10: 65,
        des: '爱你',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x5e',
        index10: 94,
        des: '不',
        nDes: 'NO',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x40',
        index10: 64,
        oDes: '好的',
        des: 'OK',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x26',
        index10: 38,
        des: '爱情',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x2f',
        index10: 47,
        des: '飞吻',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x5f',
        index10: 95,
        des: '跳跳',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x47',
        index10: 71,
        des: '发抖',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x60',
        index10: 96,
        des: '怄火',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x61',
        index10: 97,
        des: '转圈',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x62',
        index10: 98,
        des: '磕头',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x63',
        index10: 99,
        des: '回头',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x64',
        index10: 100,
        des: '跳绳',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x4f',
        index10: 79,
        des: '挥手',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x65',
        index10: 101,
        des: '激动',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x66',
        index10: 102,
        des: '街舞',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x67',
        index10: 103,
        des: '献吻',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x68',
        index10: 104,
        des: '左太极',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x69',
        index10: 105,
        des: '右太极',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x70',
        index10: 112,
        des: 'K歌',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x74',
        index10: 116,
        des: '喝彩',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x76',
        index10: 118,
        des: '爆筋',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x77',
        index10: 119,
        des: '棒棒糖',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x78',
        index10: 120,
        des: '喝奶',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x7b',
        index10: 123,
        des: '飞机',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0x82',
        index10: 130,
        des: '钞票',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0x8c',
        index10: 140,
        des: '药',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0x8d',
        index10: 141,
        des: '手枪',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xb4',
        index10: 180,
        des: '蛋',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xb0',
        index10: 176,
        des: '河蟹',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xb1',
        index10: 177,
        des: '羊驼',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xb6',
        index10: 182,
        des: '菊花',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xb3',
        index10: 179,
        des: '幽灵',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xb9',
        index10: 185,
        des: '大笑',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0x8f',
        index10: 143,
        des: '不开心',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0x92',
        index10: 146,
        des: '冷漠',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0x93',
        index10: 147,
        des: '呃',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0x94',
        index10: 148,
        des: '好棒',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0x95',
        index10: 149,
        des: '拜托',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0x96',
        index10: 150,
        des: '点赞',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0x97',
        index10: 151,
        des: '无聊',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0x98',
        index10: 152,
        des: '托脸',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0x99',
        index10: 153,
        des: '吃',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0x9a',
        index10: 154,
        des: '送花',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0x9b',
        index10: 155,
        des: '害怕',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0x9c',
        index10: 156,
        des: '花痴',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0x9d',
        index10: 157,
        des: '小样儿',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0x9f',
        index10: 159,
        des: '飙泪',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xa0',
        index10: 160,
        des: '我不看',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0xa2',
        index10: 162,
        des: '敲开心',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0xa3',
        index10: 163,
        des: '震惊',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0xa4',
        index10: 164,
        des: '让我康康',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0x96',
        index10: 150,
        des: '汗',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0x97',
        index10: 151,
        des: '打脸',
    },
    {
        flag: '0x14',
        group: 'c4',
        index: '0x98',
        index10: 152,
        des: '击掌',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x96',
        index10: 150,
        des: '头撞击',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x97',
        index10: 151,
        des: '甩头',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x98',
        index10: 152,
        des: '扔狗',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xbb',
        index10: 187,
        des: '糊脸',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x91',
        index10: 145,
        des: '偷看',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x86',
        index10: 134,
        des: '拍桌',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xba',
        index10: 186,
        des: '啵啵',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xbd',
        index10: 189,
        des: '扯一扯',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x94',
        index10: 148,
        des: '喷脸',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xbc',
        index10: 188,
        des: '拍头',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xbe',
        index10: 190,
        des: '舔一舔',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x89',
        index10: 137,
        des: '干杯',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x92',
        index10: 146,
        des: '扇脸',
    },
    {
        flag: '0x14',
        group: 'c2',
        index: '0xbf',
        index10: 191,
        des: '蹭一蹭',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x85',
        index10: 133,
        des: '撩一撩',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x8b',
        index10: 139,
        des: '哼',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x8d',
        index10: 141,
        des: '掐一掐',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x81',
        index10: 129,
        des: '顶呱呱',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x82',
        index10: 130,
        des: '抱抱',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x93',
        index10: 147,
        des: '原谅',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x8c',
        index10: 140,
        des: '佛系',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x80',
        index10: 128,
        des: '拽炸天',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x8f',
        index10: 143,
        des: '颤抖',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x95',
        index10: 149,
        des: '生日快乐',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x8a',
        index10: 138,
        des: '嘲讽',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x84',
        index10: 132,
        des: '开枪',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x90',
        index10: 144,
        des: '啃头',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x88',
        index10: 136,
        des: '恭喜',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x8e',
        index10: 142,
        des: '惊呆',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x83',
        index10: 131,
        des: '暴击',
    },
    {
        flag: '0x14',
        group: 'c3',
        index: '0x87',
        index10: 135,
        des: '拍手',
    },
    {
        flag: '0x14',
        group: 'none',
        index: '0x5b',
        index10: 91,
        des: '吓',
    },
];
